### ISSUE TITLE
streamKM counter problem

### ISSUE THREAD

**Issue by ioanna-ki** [huawei-noah/streamDM#94] opened 2018-04-26 15:20 UTC
I am new in this kind of programming but I think streamKM has an issue since train method has a numInstances counter inside a foreachRDD. The value of numInstances is not stored and as a result getClusters method does not work properly.  Any thoughts? 

    /** 
      *  Maintain the BucketManager for coreset extraction, given an input DStream of Example.
      * @param input a stream of instances
      */
     def train(input: DStream[Example]): Unit = {
       input.foreachRDD(rdd => {
         rdd.foreach(ex => {
           bucketmanager = bucketmanager.update(ex)
           numInstances += 1
         })
       })
     }

**Comment by hmgomes** [comment] 2018-04-26 16:29
Hi @ioanna-ki,

`numInstances` is a var defined within the scope of `StreamKM` class, specifically in [here](https://github.com/huawei-noah/streamDM/blob/e5d50a5e39f64ed7e0db38d8d8aab6497bea0144/src/main/scala/org/apache/spark/streamdm/clusterers/StreamKM.scala#L45), thus updates to it are stored. Perhaps you observed a different error? 

Best Regards, 
Heitor

**Comment by ioanna-ki** [comment] 2018-04-29 18:04
well I call ClusteringTrainEvaluate with StreamKM as a parameter and text files as an input. The thing is that inside getClusters of StreamKM the paramater numInstances is always zero. I didn't change the code at all. Am I calling the app wrong? 

the input that I use is in this form:
1.0 1.0 1.0
2.0 2.0 1.0
etc...

**Comment by hmgomes** [comment] 2018-04-30 15:57
Please show me the command line you used

Best Regards, 
Heitor

**Comment by ioanna-ki** [comment] 2018-04-30 20:07
./scripts/spark.sh "ClusteringTrainEvaluate -c (StreamKM) -s (TextStreamReader) 

and the data input is randomtreesampledata.txt 
eg. 

> 0.0 4.0,2.0,2.0,2.0,1.0,0.8060225109830121,0.9043923203457621,0.8116905753399468,0.35912458818647686,0.2256564761176031
etc...

**Comment by hmgomes** [comment] 2018-05-01 14:53
Hi @ioanna-ki 

Apparently the issue is related to TextStreamReader and not StreamKM, for example, using FileReader with an arff file should work, e.g.: 

./spark.sh "ClusteringTrainEvaluate -c (StreamKM) -s (FileReader -f ../data/iris.arff -k 10 -d 10 -i 150)" 1> result_iris_streamKM.txt 2> log_iris_streamKM.log

Please check if this one works and let me know. 

Best Regards, 
Heitor

**Comment by ioanna-ki** [comment] 2018-05-01 15:50
I got an error message. I attached the log here -> [log_iris_streamKM.log](https://github.com/huawei-noah/streamDM/files/1964285/log_iris_streamKM.log)

**Comment by ioanna-ki** [comment] 2018-05-01 16:31
Ok I run the same on socketTextStreamReader I am getting  SSE=680.82440 as a result for iris.arff, but kmeans cluster method is never called and numInstances is zero, also if I print clpairs (the output stream of type (Example,Double)) example has a value, but double (where I am guessing is the center of the cluster) is always zero

**Comment by ioanna-ki** [comment] 2018-05-01 18:32
I'll try to fix it,
thanks for your time Heitor.

**Comment by hmgomes** [comment] 2018-05-01 18:41
No problem and I am glad you provided all the details and helped uncovering this. 
I will close this now and we can create another issue later following the template (similar to this one #84)

Best Regards, 
Heitor

**Closed by hmgomes** 2018-05-01 18:41 UTC
